version: '2'

services:
  app-db:
    image: 'postgres:latest'
    container_name: app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  appRedis:
    image: redis:latest
    container_name: appRedis
    ports:
      - '6379:6379'
  promotion:
    image: 'promotion:latest'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app-db
      - appRedis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-db:5432/postgres?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_REDIS_H=appRedis
    ports:
      - "8081:8081"
